name: Test Automation Actions DotNet

on: 
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  Job-DotNet-Push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.302  # Reemplaza con tu versión de .NET
      
      - name: Unit Tests 
        run: dotnet test Implementacion/Codigo/Backend/PharnaGo.Test

