name: Test Automation Actions DotNet

on: 
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  Job-DotNet-Push:
    runs-on: windows-latest
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Unit Tests 
        run: dotnet test Implementacion/Codigo/Backend/PharnaGo.Test
